name: deploy-firebase-functions

on:
  push:
    branches: [main]
    paths:
      - 'functions/**'
      - 'firebase.json'
      - '.github/workflows/deploy-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & build functions
        run: |
          cd functions
          npm ci
          npm run build

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions --non-interactive
