name: format-and-lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint -- --max-warnings=0